# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celling',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('color', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('celling_width', models.IntegerField()),
            ],
        ),
    ]
