# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 12:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Celling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('celling_width', models.IntegerField()),
                ('price', models.FloatField(default=0.0)),
                ('for_remove', models.BooleanField(default=False)),
                ('count_meters_pagon', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dealer_name', models.CharField(max_length=100)),
                ('dealer_phone', models.CharField(max_length=13, unique=True)),
                ('dealer_email', models.CharField(max_length=150, unique=True)),
                ('dealer_firm_name', models.CharField(max_length=100, null=True)),
                ('dealer_address', models.CharField(max_length=100, null=True)),
                ('dealer_unp', models.CharField(max_length=9, null=True)),
                ('dealer_amount', models.FloatField(default=0.0)),
                ('user_id', models.BigIntegerField()),
                ('max_deposit', models.FloatField(default=500.0)),
                ('for_remove', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialColor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('for_remove', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialDealerPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('discount', models.FloatField(default=0.0, null=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_site.Dealer')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('default_price', models.FloatField(default=0.0)),
                ('colors', models.ManyToManyField(default=None, to='test_site.MaterialColor')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s_celling', models.FloatField(null=True)),
                ('p_celling', models.FloatField(null=True)),
                ('p_garpun', models.FloatField(null=True)),
                ('p_curve', models.FloatField(null=True)),
                ('material_long', models.FloatField(default=0.0, null=True)),
                ('celling_price', models.FloatField(null=True)),
                ('order_status', models.IntegerField(default=1)),
                ('order_date', models.DateField(default=datetime.datetime.now)),
                ('for_remove', models.BooleanField(default=False)),
                ('celling', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_site.Celling')),
                ('color', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_site.MaterialColor')),
                ('dealer_obj', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_site.Dealer')),
                ('material_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_site.MaterialGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sum', models.FloatField(default=0.0)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_site.Dealer')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=256)),
                ('property_value', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='materialdealerprice',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_site.MaterialGroup'),
        ),
        migrations.AddField(
            model_name='celling',
            name='material_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_site.MaterialGroup'),
        ),
        migrations.AddField(
            model_name='balance',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_site.Dealer'),
        ),
    ]
