# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('celling_id', models.BigIntegerField()),
                ('client_id', models.BigIntegerField()),
                ('s_celling', models.FloatField(null=True)),
                ('p_celling', models.FloatField(null=True)),
                ('p_garpun', models.FloatField(null=True)),
                ('p_curve', models.FloatField(null=True)),
            ],
        ),
    ]
