# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0003_auto_20170920_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celling',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
