# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0004_auto_20170921_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celling',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
