# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0005_auto_20171017_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='s_material',
            field=models.FloatField(default=0.0),
        ),
    ]
