# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0005_auto_20170921_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dialer_name', models.CharField(max_length=100)),
                ('dialer_discount_percent', models.IntegerField()),
                ('dialer_phone', models.CharField(max_length=13, unique=True)),
                ('dialer_address', models.CharField(max_length=100)),
                ('user_id', models.BigIntegerField(unique=True)),
            ],
        ),
    ]
