# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0006_dialer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialer',
            name='dialer_discount_percent',
        ),
    ]
