# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0008_order_celling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(default=1),
        ),
    ]
