# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0009_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dialer',
            name='dialer_email',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='dialer',
            name='dialer_firm_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dialer',
            name='dialer_unp',
            field=models.CharField(default='', max_length=9),
        ),
    ]
