# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0010_auto_20170925_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dialer_name', models.CharField(max_length=100)),
                ('dialer_phone', models.CharField(max_length=13, unique=True)),
                ('dialer_email', models.CharField(max_length=150, unique=True)),
                ('dialer_firm_name', models.CharField(max_length=100, null=True)),
                ('dialer_address', models.CharField(max_length=100, null=True)),
                ('dialer_unp', models.CharField(max_length=9, null=True)),
                ('user_id', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Dialer',
        ),
    ]
