# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0011_auto_20170926_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealer',
            old_name='dialer_address',
            new_name='dealer_address',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='dialer_email',
            new_name='dealer_email',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='dialer_firm_name',
            new_name='dealer_firm_name',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='dialer_name',
            new_name='dealer_name',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='dialer_phone',
            new_name='dealer_phone',
        ),
        migrations.RenameField(
            model_name='dealer',
            old_name='dialer_unp',
            new_name='dealer_unp',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='dealer_id',
        ),
    ]
