# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0012_auto_20170926_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='dealer_amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
