# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0013_dealer_dealer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='celling',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
