# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0014_celling_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDealerPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dealer_id', models.BigIntegerField()),
                ('material_id', models.BigIntegerField()),
                ('discount', models.FloatField(default=0.0, null=True)),
            ],
        ),
    ]
