# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0016_auto_20170927_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialdealerprice',
            name='dealer_id',
        ),
        migrations.RemoveField(
            model_name='materialdealerprice',
            name='material_id',
        ),
        migrations.AddField(
            model_name='dealer',
            name='materials',
            field=models.ManyToManyField(through='test_site.MaterialDealerPrice', to='test_site.Celling'),
        ),
        migrations.AddField(
            model_name='materialdealerprice',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_site.Dealer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialdealerprice',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_site.Celling'),
            preserve_default=False,
        ),
    ]
