# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0018_auto_20170928_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
