# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0020_materialgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='celling',
            name='material_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_site.MaterialGroup'),
            preserve_default=False,
        ),
    ]
