# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0022_auto_20170929_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sum', models.FloatField(default=0)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_site.Dealer')),
            ],
        ),
    ]
