# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0024_order_dealer_obj'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialColor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='materialgroup',
            name='default_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='celling',
            name='colors',
            field=models.ManyToManyField(default=None, to='test_site.MaterialColor'),
        ),
    ]
