# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0026_auto_20171001_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='celling',
            name='color',
        ),
        migrations.RemoveField(
            model_name='celling',
            name='colors',
        ),
        migrations.AddField(
            model_name='celling',
            name='count_meters_pagon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='materialgroup',
            name='colors',
            field=models.ManyToManyField(default=None, to='test_site.MaterialColor'),
        ),
    ]
