# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0030_dealer_max_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dealer_obj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='test_site.Dealer'),
        ),
    ]
