# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0031_auto_20171002_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='material_long',
            field=models.FloatField(default=0.0),
        ),
    ]
