# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 00:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0032_order_material_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='material_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_site.MaterialGroup'),
        ),
    ]
