# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0034_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialcolor',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
