# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0035_auto_20171002_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.FloatField(default=0.0)),
            ],
        ),
    ]
