# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-02 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0036_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='celling',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_site.Celling'),
        ),
    ]
