# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0037_auto_20171002_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dealer_id',
        ),
    ]
