# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0039_auto_20171004_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_site.Dealer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='material_long',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
