# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0041_auto_20171005_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celling',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
