# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0042_auto_20171009_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialdealerprice',
            name='dealer_id',
        ),
        migrations.RemoveField(
            model_name='materialdealerprice',
            name='material_id',
        ),
        migrations.AddField(
            model_name='materialdealerprice',
            name='dealer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_site.Dealer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materialdealerprice',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='test_site.Celling'),
            preserve_default=False,
        ),
    ]
