# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0043_auto_20171009_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialdealerprice',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_site.MaterialGroup'),
        ),
    ]
