# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0044_auto_20171009_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcolor',
            name='for_remove',
            field=models.BooleanField(default=False),
        ),
    ]
